services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: gainz:${GAINZ_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      GAINZ_HOST: 0.0.0.0
      GAINZ_DB_HOST: gainz-db
      GAINZ_DB_PORT: 27017
      GAINZ_DB_USER: gainz
      GAINZ_DB_PASS: gainz
      GAINZ_DB_BASE: admin
      GAINZ_REDIS_HOST: gainz-redis
  db:
    image: mongo:7.0
    hostname: gainz-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "gainz"
      MONGO_INITDB_ROOT_PASSWORD: "gainz"
    command: "mongod"
    volumes:
      - gainz-db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 40

  redis:
    image: bitnami/redis:6.2.5
    hostname: "gainz-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50



volumes:
  gainz-db-data:
    name: gainz-db-data
